#include <jni.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <inttypes.h>
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <sstream>
#include <vector>
#include <map>
#include <iomanip>
#include <thread>
#include <sys/resource.h>
#include <sys/uio.h>
#include <fcntl.h>
#include <android/log.h>
#include <dirent.h>
#include <list>
#include <libgen.h>
#include <locale>
#include <codecvt>
#include <sys/wait.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/un.h>
#include <unistd.h>
#include <cstring>
#include <elf.h>
#include <link.h>
#include <dlfcn.h>
#include <cstdio>
#include <sys/mman.h>
#include <fcntl.h>
#include <pthread.h>
#include <codecvt>
#include <chrono>
#include <queue>
#include <unistd.h>
#include <cstring>
#include <elf.h>
#include <link.h>
#include <dlfcn.h>
#include <cstdio>
#include <fcntl.h>
#include <pthread.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>
#include <fcntl.h>
#include <unordered_set>
#include <android/log.h>